[cite_start]name: Flujo_trabajo [cite: 10]

on:
  push:
    branches:
      - [cite_start]main [cite: 12, 13, 14, 15]

jobs:
  [cite_start]example-job: [cite: 18, 20]
    [cite_start]runs-on: ubuntu-latest [cite: 22]
    
    steps:
      - [cite_start]name: Checkout code [cite: 26]
        [cite_start]uses: actions/checkout@v3 [cite: 27]

      - [cite_start]name: Use Personal Access Token [cite: 63]
        run: |
          curl -H "Authorization: Bearer ${{ secrets.PATH_SECRET }}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/user/repos [cite: 65, 66, 67, 68]
